#!/bin/bash
me=$(whoami)
pwd=$(pwd)
dockerpath="/var/www/html"
container=$(docker ps|grep "$me"|grep "php"|awk '{print $1}')
command="docker exec -w $dockerpath -it $container php ${*}"
echo -e "\n${command}\n"

eval $command


