#!/bin/bash
me=$(whoami)
pwd=$(pwd)
dockerpath=$(echo $pwd| sed -e 's/.*bokeh/\/var\/www\/html/g')
container=$(docker ps|grep "$me"|grep "php"|awk '{print $1}')
command="docker exec -w $dockerpath -it $container phpunit ${*}"
echo -e "\n${command}\n"

eval $command


