#!/bin/bash
dockerpath="/var/www/html"
container=$(docker inspect -f '{{ .Name }}' $HOSTNAME| cut -c 2-| sed 's/-emacs-/-php-/')
args=$(echo ${*}| sed -e 's/\/[0-9a-zA-Z\/]\+\/bokeh/\/var\/www\/html/g')
command="docker exec -w $dockerpath -it $container php ${args}"
echo -e "\n${command}\n"

eval $command


